spring:
  application:
    name: service-a
  data:
    rest:
      base-path: /apiA
server:
  port: 8800
eureka:
  instance:
    instance-id: inst001
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

